-
  # SSH连接配置，uri格式
  uri: ssh://root:123456@192.168.1.55:22
  # 隧道转发配置
  tunnels:
    -
      # 开启隧道的远程主机配置，格式为【IP地址:端口】
      remote: 127.0.0.1:27017
      # 开启隧道映射到本地的配置，格式为【IP地址:端口】
      local: 0.0.0.0:27017
    -
      remote: 127.0.0.1:6379
      local: 0.0.0.0:6379